plugins {
    id("dev.kikugie.stonecutter")
}

stonecutter.active "26.2"

tasks.register("publishModrinth") {
    group = "publishing"
    description = "Publishes all Minecraft versions to Modrinth"

    subprojects.forEach {sub ->
        if (sub.findProperty("stonecutter.redirect") == null) {
            dependsOn(sub.tasks.named("modrinth"))
        }
    }
}

tasks.register("buildAll") {
    group = "build"
    description = "Builds all Minecraft versions"

    subprojects.forEach {sub ->
        if (sub.findProperty("stonecutter.redirect") == null) {
            dependsOn(sub.tasks.named("build"))
        }
    }
}